#!/usr/bin/env python3
# SPDX-License-Identifier: AGPL-3.0-or-later
#
# AI-GENERATED CODE NOTICE:
# This source code was generated by OpenAI ChatGPT for the
# urbackup-proxmox-agent project. It has NOT been reviewed by a human
# software developer. Use only after testing in a non-production environment.
#
# Copyright (C) 2026 K4 DIGITAL GmbH contributors

import argparse
import json
import sys
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
if str(SCRIPT_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPT_DIR))

from discover_vm_backup_set import discover


ROLE_ORDER = {"disk": 0, "efi": 1, "tpm": 2}
TRANSIENT_VM_CONFIG_KEYS = {"parent", "lock"}


def sanitize_vm_config(config_text: str) -> str:
    """Remove transient Proxmox runtime/snapshot fields from restore metadata."""
    lines = []
    for line in config_text.splitlines():
        if ":" in line:
            key = line.split(":", 1)[0].strip()
            if key in TRANSIENT_VM_CONFIG_KEYS:
                continue
        lines.append(line)
    return "\n".join(lines) + ("\n" if config_text.endswith("\n") else "")


def build_plan(vmid: int) -> dict:
    discovered = discover(vmid)

    image_jobs = []
    for device in discovered["devices"]:
        if not device.get("supported_v1"):
            continue
        image_jobs.append({
            "device_key": device["key"],
            "role": device["role"],
            "source": device["path"],
            "storage_ref": device["storage_ref"],
            "urbackup_image_source": device["path"],
        })

    image_jobs.sort(
        key=lambda item: (
            ROLE_ORDER.get(item["role"], 99),
            item["device_key"],
        )
    )

    return {
        "version": 1,
        "vmid": vmid,
        "storage_scope": discovered["storage_scope"],
        "supported_v1": discovered["supported_v1"],
        "metadata": {
            "vm_config": sanitize_vm_config(discovered["vm_config"]),
        },
        "image_jobs": image_jobs,
        "skipped": discovered["skipped"],
        "unsupported_devices": discovered["unsupported_devices"],
    }


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Build a VM-centric UrBackup image plan for a Proxmox VM"
    )
    parser.add_argument("vmid", type=int)
    parser.add_argument(
        "--compact",
        action="store_true",
        help="Emit compact JSON instead of indented JSON",
    )
    args = parser.parse_args()

    try:
        plan = build_plan(args.vmid)
        if args.compact:
            json.dump(plan, sys.stdout, sort_keys=True, separators=(",", ":"))
        else:
            json.dump(plan, sys.stdout, indent=2, sort_keys=True)
        sys.stdout.write("\n")
        return 0 if plan["supported_v1"] else 2
    except Exception as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
