#!/usr/bin/env python3
# SPDX-License-Identifier: AGPL-3.0-or-later
#
# AI-GENERATED CODE NOTICE:
# This source code was generated by OpenAI ChatGPT for the
# urbackup-proxmox-agent project. It has NOT been reviewed by a human
# software developer. Use only after testing in a non-production environment.
#
# Copyright (C) 2026 K4 DIGITAL GmbH contributors

import argparse
import json
import re
import subprocess
import sys
from typing import Dict, List


PAYLOAD_KEY_RE = re.compile(r"^(?:scsi|sata|virtio|ide)\\d+$|^(?:efidisk|tpmstate)\\d+$")
ZVOL_PREFIX = "/dev/zvol/"


def run(cmd: List[str], check: bool = True) -> subprocess.CompletedProcess:
    proc = subprocess.run(cmd, text=True, capture_output=True)
    if check and proc.returncode != 0:
        raise RuntimeError(
            f"Command failed ({proc.returncode}): {' '.join(cmd)}\n"
            f"stdout: {proc.stdout.strip()}\n"
            f"stderr: {proc.stderr.strip()}"
        )
    return proc


def device_role(key: str) -> str:
    if key.startswith("efidisk"):
        return "efi"
    if key.startswith("tpmstate"):
        return "tpm"
    return "disk"


def discover(vmid: int) -> Dict[str, object]:
    config_text = run(["qm", "config", str(vmid)]).stdout
    devices: List[Dict[str, object]] = []
    skipped: List[Dict[str, str]] = []

    for raw_line in config_text.splitlines():
        if ":" not in raw_line:
            continue

        key, raw_value = raw_line.split(":", 1)
        key = key.strip()
        value = raw_value.strip()

        if not PAYLOAD_KEY_RE.match(key):
            continue

        if "media=cdrom" in value:
            skipped.append({
                "key": key,
                "reason": "cdrom",
                "config": value,
            })
            continue

        storage_ref = value.split(",", 1)[0]
        path_result = run(["pvesm", "path", storage_ref], check=False)

        if path_result.returncode != 0:
            devices.append({
                "key": key,
                "role": device_role(key),
                "storage_ref": storage_ref,
                "path": None,
                "zfs": False,
                "supported_v1": False,
                "error": (path_result.stderr or path_result.stdout).strip(),
            })
            continue

        path = path_result.stdout.strip()
        is_zfs = path.startswith(ZVOL_PREFIX)
        devices.append({
            "key": key,
            "role": device_role(key),
            "storage_ref": storage_ref,
            "path": path,
            "zfs": is_zfs,
            "supported_v1": is_zfs,
        })

    payload = [d for d in devices if d["role"] == "disk"]
    efi = [d for d in devices if d["role"] == "efi"]
    tpm = [d for d in devices if d["role"] == "tpm"]

    unsupported = [d for d in devices if not d["supported_v1"]]

    return {
        "version": 1,
        "vmid": vmid,
        "storage_scope": "zfs-only",
        "vm_config": config_text,
        "devices": devices,
        "backup_set": {
            "disks": payload,
            "efi": efi,
            "tpm": tpm,
        },
        "skipped": skipped,
        "supported_v1": bool(devices) and not unsupported,
        "unsupported_devices": unsupported,
    }


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Discover the ZFS-backed backup set for a Proxmox VM"
    )
    parser.add_argument("vmid", type=int)
    parser.add_argument(
        "--compact",
        action="store_true",
        help="Emit compact JSON instead of indented JSON",
    )
    args = parser.parse_args()

    try:
        result = discover(args.vmid)
        if args.compact:
            json.dump(result, sys.stdout, sort_keys=True, separators=(",", ":"))
        else:
            json.dump(result, sys.stdout, indent=2, sort_keys=True)
        sys.stdout.write("\n")
        return 0 if result["supported_v1"] else 2
    except Exception as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
