#!/usr/bin/env python3
# SPDX-License-Identifier: AGPL-3.0-or-later
#
# AI-GENERATED CODE NOTICE:
# This source code was generated by OpenAI ChatGPT for the
# urbackup-proxmox-agent project. It has NOT been reviewed by a human
# software developer. Use only after testing in a non-production environment.
#
# Copyright (C) 2026 K4 DIGITAL GmbH contributors
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

import argparse
import fcntl
import json
import os
import re
import subprocess
import sys
import time
from pathlib import Path
from typing import Dict, List, Tuple

STATE_DIR = Path("/run/urbackup-proxmox-agent")
LOCK_DIR = STATE_DIR / "locks"
ZVOL_PREFIX = "/dev/zvol/"
ZVOL_VM_RE = re.compile(r"^/dev/zvol/(?P<dataset>.+/vm-(?P<vmid>[0-9]+)-disk-[0-9]+)$")


def run(cmd: List[str], check: bool = True) -> subprocess.CompletedProcess:
    proc = subprocess.run(cmd, text=True, capture_output=True)
    if check and proc.returncode != 0:
        raise RuntimeError(
            f"Command failed ({proc.returncode}): {' '.join(cmd)}\n"
            f"stdout: {proc.stdout.strip()}\n"
            f"stderr: {proc.stderr.strip()}"
        )
    return proc


def safe_id(value: str) -> str:
    sanitized = re.sub(r"[^A-Za-z0-9_.-]", "_", value)
    if not sanitized:
        raise ValueError("Empty snapshot identifier")
    return sanitized[:120]


def snapshot_name(snapshot_id: str) -> str:
    compact = re.sub(r"[^A-Za-z0-9]", "", snapshot_id)
    if not compact:
        raise ValueError("Snapshot identifier has no usable characters")
    return f"urbackup_{compact[:24]}"


def state_path(snapshot_id: str) -> Path:
    return STATE_DIR / f"{safe_id(snapshot_id)}.json"


def ensure_dirs() -> None:
    STATE_DIR.mkdir(mode=0o700, parents=True, exist_ok=True)
    LOCK_DIR.mkdir(mode=0o700, parents=True, exist_ok=True)


def vm_lock(vmid: int):
    ensure_dirs()
    lock_path = LOCK_DIR / f"vm-{vmid}.lock"
    handle = open(lock_path, "a+", encoding="utf-8")
    fcntl.flock(handle.fileno(), fcntl.LOCK_EX)
    return handle


def parse_zvol_vm(path: str) -> Tuple[int, str]:
    match = ZVOL_VM_RE.match(path)
    if not match:
        raise ValueError(
            "Proxmox UrBackup hook only accepts VM ZVOL devices matching "
            "/dev/zvol/.../vm-<vmid>-disk-<n>"
        )
    return int(match.group("vmid")), match.group("dataset")


def get_snapdev(dataset: str) -> Tuple[str, str]:
    out = run(["zfs", "get", "-H", "-o", "value,source", "snapdev", dataset]).stdout.rstrip("\n")
    value, source = out.split("\t", 1)
    return value, source


def restore_snapdev(dataset: str, value: str, source: str) -> None:
    if source == "local":
        run(["zfs", "set", f"snapdev={value}", dataset])
    else:
        run(["zfs", "inherit", "snapdev", dataset])


def get_vm_zvols(vmid: int) -> List[Dict[str, str]]:
    cfg = run(["qm", "config", str(vmid)]).stdout
    devices: List[Dict[str, str]] = []
    for line in cfg.splitlines():
        if ":" not in line:
            continue
        key, value = line.split(":", 1)
        key = key.strip()
        value = value.strip()
        if "media=cdrom" in value:
            continue
        if not key.startswith(("scsi", "sata", "virtio", "efidisk", "tpmstate")):
            continue
        storage_ref = value.split(",", 1)[0]
        p = run(["pvesm", "path", storage_ref], check=False)
        if p.returncode != 0:
            continue
        dev = p.stdout.strip()
        if not dev.startswith(ZVOL_PREFIX):
            continue
        dataset = dev[len(ZVOL_PREFIX):]
        devices.append({"key": key, "storage_ref": storage_ref, "path": dev, "dataset": dataset})
    if not devices:
        raise RuntimeError(f"No ZFS-backed payload devices found for VM {vmid}")
    return devices


def wait_for_path(path: str, timeout: float = 15.0) -> None:
    deadline = time.monotonic() + timeout
    while time.monotonic() < deadline:
        if os.path.exists(path):
            return
        time.sleep(0.2)
    raise RuntimeError(f"Snapshot block device did not appear: {path}")


def atomic_write_json(path: Path, data: dict) -> None:
    tmp = path.with_suffix(path.suffix + ".tmp")
    with open(tmp, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2, sort_keys=True)
        f.write("\n")
        f.flush()
        os.fsync(f.fileno())
    os.chmod(tmp, 0o600)
    os.replace(tmp, path)


def cleanup_state(state: dict, remove_state_file: bool = True) -> None:
    vmid = int(state["vmid"])
    snap = state["snapshot_name"]
    errors: List[str] = []
    for item in reversed(state.get("devices", [])):
        try:
            restore_snapdev(item["dataset"], item["snapdev_value"], item["snapdev_source"])
        except Exception as exc:
            errors.append(f"restore snapdev {item['dataset']}: {exc}")
    deletion = run(["qm", "delsnapshot", str(vmid), snap], check=False)
    if deletion.returncode != 0:
        combined = (deletion.stderr or deletion.stdout).strip()
        if "does not exist" not in combined.lower() and "no such" not in combined.lower():
            errors.append(f"qm delsnapshot: {combined}")
    if remove_state_file:
        try:
            state_path(state["snapshot_id"]).unlink(missing_ok=True)
        except Exception as exc:
            errors.append(f"remove state file: {exc}")
    if errors:
        raise RuntimeError("; ".join(errors))


def create(snapshot_id: str, requested_path: str) -> int:
    ensure_dirs()
    vmid, requested_dataset = parse_zvol_vm(requested_path)
    lock = vm_lock(vmid)
    try:
        spath = state_path(snapshot_id)
        if spath.exists():
            with open(spath, "r", encoding="utf-8") as f:
                existing = json.load(f)
            if int(existing.get("vmid", -1)) != vmid:
                raise RuntimeError("Snapshot id is already associated with a different VM")
            target = f"{requested_path}@{existing['snapshot_name']}"
            wait_for_path(target)
            print(f"SNAPSHOT={target}")
            return 0

        snap = snapshot_name(snapshot_id)
        devices = get_vm_zvols(vmid)
        if requested_dataset not in {item["dataset"] for item in devices}:
            raise RuntimeError(f"Requested device is not part of VM {vmid}: {requested_path}")

        state = {
            "version": 1,
            "snapshot_id": snapshot_id,
            "snapshot_name": snap,
            "vmid": vmid,
            "requested_path": requested_path,
            "devices": [],
        }
        created = False
        try:
            for item in devices:
                value, source = get_snapdev(item["dataset"])
                enriched = dict(item)
                enriched["snapdev_value"] = value
                enriched["snapdev_source"] = source
                state["devices"].append(enriched)

            run(["qm", "snapshot", str(vmid), snap, "--description", "UrBackup Proxmox image snapshot"])
            created = True

            for item in state["devices"]:
                run(["zfs", "set", "snapdev=visible", item["dataset"]])

            target = f"{requested_path}@{snap}"
            wait_for_path(target)
            atomic_write_json(spath, state)
            print(f"SNAPSHOT={target}")
            print(f"Proxmox VM {vmid} snapshot {snap} created for UrBackup", file=sys.stderr)
            return 0
        except Exception:
            if created:
                try:
                    cleanup_state(state, remove_state_file=False)
                except Exception as cleanup_exc:
                    print(f"WARNING: rollback failed: {cleanup_exc}", file=sys.stderr)
            raise
    finally:
        lock.close()


def remove(snapshot_id: str) -> int:
    ensure_dirs()
    spath = state_path(snapshot_id)
    if not spath.exists():
        print(f"No Proxmox snapshot state found for {snapshot_id}; cleanup is already complete", file=sys.stderr)
        return 0
    with open(spath, "r", encoding="utf-8") as f:
        state = json.load(f)
    vmid = int(state["vmid"])
    lock = vm_lock(vmid)
    try:
        cleanup_state(state)
        print(f"Proxmox VM {vmid} snapshot {state['snapshot_name']} removed after UrBackup image", file=sys.stderr)
        return 0
    finally:
        lock.close()


def main() -> int:
    parser = argparse.ArgumentParser(description="UrBackup Proxmox ZVOL snapshot hook")
    sub = parser.add_subparsers(dest="command", required=True)
    create_p = sub.add_parser("create")
    create_p.add_argument("snapshot_id")
    create_p.add_argument("requested_path")
    remove_p = sub.add_parser("remove")
    remove_p.add_argument("snapshot_id")
    args = parser.parse_args()
    try:
        if args.command == "create":
            return create(args.snapshot_id, args.requested_path)
        return remove(args.snapshot_id)
    except Exception as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
